### PR TITLE
Add array.aggregate function

### LINKED ISSUE #532: Array reduction
Hi,

I'm looking for a way to reduce arrays, e.g. I was hoping for something like this:

```
total_length = ["Apple", "Banana", "Computer", "Mobile Phone", "Orange", "Sofa", "Table"] | array.each @string.size | array.reduce @math.plus
```

Or in the case of summing, just 
```
total_length = ["Apple", "Banana", "Computer", "Mobile Phone", "Orange", "Sofa", "Table"] | array.each @string.size | math.plus
```

But I can't find an obvious way. Is array reduction missing?

### PR DESCRIPTION
**Pull request by igitur**
Fixes #532 

Instead of a reduce function, I implemented `array.aggregate`, that also accept an initial seed value. I could add more tests if you want to. Just point me to the applicable spot in the test suite where this would be required.

### CODE REVIEW

**Comment by igitur** [comment]
And if you're happy with this approach, I'd like to implement more LINQ-ish array functions. `array.sum`, `array.average`, `array.all`, `array.any`, `array.min`, `array.max` and maybe `array.groupby`.

**Comment by xoofx** [comment]
Oh definitely, you can add them as part of this PR

**Comment by r-Larch** [comment]
Hi,

I really appreciate these additions; great work!

I reviewed the `array.aggregate` implementation and believe it could be improved by making the seed value optional. Making the seed value optional can enhance flexibility and usability for cases where the initial value isn't necessary or when the user prefers the aggregation to start directly with the elements of the array. Specifically, if no seed value is provided, it would be beneficial to automatically use the first item of the list as the `current` value and the second item as the `next` value. This approach simplifies the function's usage for common aggregation tasks, such as summing values or concatenating strings, where the natural starting point is the first element of the array. It also aligns with the behavior of similar functions in other programming languages, making it more intuitive for users transitioning from different backgrounds.

What do you think?

**Comment by igitur** [comment]
@r-Larch I played around with that idea. The order if the 2 parameters would need to swap from seed & function to function and optional seed. Right? But when I tried that with the seed provided, the function consumes the seed instead of it being passed into `array.aggregate`. Not sure if it's a bug or by design.

**Comment by igitur** [comment]
Maybe just easier to implement `array.reduce`, which wouldn't have the seed parameter.

**Comment by r-Larch** [comment]
> @r-Larch I played around with that idea. The order if the 2 parameters would need to swap from seed & function to function and optional seed. Right? But when I tried that with the seed provided, the function consumes the seed instead of it being passed into `array.aggregate`. Not sure if it's a bug or by design.

Hmm.. for me it looks like a bug but I don't know.

Does it work with parameters like this: (seed optional before func)
|Method|Desc|
|-|-| 
| `array.aggregate <func(c, n)>` | no seed, just a func param | 
| `array.aggregate <seed> <func(c, n)>` | seed + func | 

In C#
```csharp
public static object Aggregate(TemplateContext context, SourceSpan span, IEnumerable list, object? arg1, object? arg2);
if (arg1 is IScriptCustomFunction) ...
if (arg2 is IScriptCustomFunction) ...
```

**Comment by xoofx** [comment]
Closing for now, as it got stale, feel free to reopen once things are better settled. Thanks!

**Pull request closed without merging**
