### PR TITLE
feat: Support targetframework .net 8

### LINKED ISSUE #546: Support library for target framework .net 8
.net 7 is Out of support versions.

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

image

### PR DESCRIPTION
**Pull request by eoehen**
close #546

### CODE REVIEW

**Comment by eoehen** [comment]
I wasn't sure if I was allowed to remove .net 7.

**Comment by xoofx** [comment]
Hey, strictly speaking it's not super important because supporting net7.0 defaults to support net8.0.

I would like to check more broadly what needs to be updated to net8.0 in the project (there are several executables...etc.)

**Comment by pvanroos** [comment]
I tried a simple console project targeting .NET 9 and it does not work.

**Comment by pvanroos** [comment]
I'll try again.  I swapped it out for Fluid in the interim.

**Pull request closed without merging**
