### PR TITLE
Add enum to pretty name #276

### PR DESCRIPTION
**Pull request by totpero**

### CODE REVIEW

**Comment by xoofx** [comment]
Thanks, could you add a small line test to https://github.com/lunet-io/scriban/blob/831a4d951325543155b3d0c3d63353c8e1d344ad/src/Scriban.Tests/TestRuntime.cs#L26-L50 ?

**Comment by xoofx** [comment]
Note that there was a bug in your implementation. It was not `== typeof(Enum)`  but `type.IsEnum`

**Comment by totpero** [comment]
Done 👍

**Comment by xoofx** [comment]
Sorry I thought that you saw that this was already fixed by commit 198ccda5caf313839b10bc986a3a9ec586b973e0

**Comment by totpero** [comment]
Ok, I didn't

**Pull request merged**
