### PR TITLE
Add support for negative numbers in 'when' statements

### PR DESCRIPTION
**Pull request by AlfredoMS**
Fix for issue #392 

This change adds support for negative numbers, both integers and float, to be added as conditions for "when" statements.

Let me know if I should add more tests.

### CODE REVIEW

**Comment by lofcz** [comment]
This should probably not be limited to `when -10` but also support cases like `when +-+-10`.

**Comment by AlfredoMS** [comment]
hey @lofcz thanks for the feedback, however I think that would be of a much bigger scope than this change intends. I think bringing functionality parity of literals and constants with negative numbers makes sense and has immediate benefits,

I am thinking adding support for full constant expression might be a good follow up change. How does that sound? Otherwise I'll start taking a look into what would it take to accomplish that, maybe if it is a short change I'll just update this PR

**Comment by lofcz** [comment]
Seems like #409 superseeds this. I would recommend to close this PR and continue discussion there.

**Comment by xoofx** [comment]
Fixed by #409 
Thanks!

**Pull request closed without merging**
